import type { Entity } from "./constants";
import { WAREHOUSES } from "./warehouses";
import { ACCOUNT_CODES, accountCodeLabels } from "./account-catalog";
import { COMPANIES } from "./companies";

export type Field = { key: string; label: string; type?: "text"|"email"|"tel"|"number"|"money"|"date"|"textarea"|"select"|"relation"|"user"|"file"|"phones"|"account"|"cashAccount"|"hidden";
  /** En un campo "account": qué cuentas del plan se ofrecen (CI para ingresos, el resto para egresos). Sin esto, todas las activas. */ direction?: "ingreso"|"egreso";
  /** Solo aparece al editar un registro que ya existe (el motivo de un cambio, por ejemplo). */ editOnly?: boolean; /** Lo calcula el sistema: se muestra pero no se edita a mano. */ readOnly?: boolean; required?: boolean; options?: string[]; relation?: Entity; placeholder?: string; hint?: string; /** Atajos "7 / 14 / 30 días" en los campos de fecha. */ quickRanges?: number[];
  /** Con qué viene cargado el campo al crear un registro nuevo. */ defaultValue?: string;
  /** Igual que `defaultValue` pero para fechas: hoy + N días. */ defaultInDays?: number;
  /** Saca el atajo "Hoy": no toda fecha puede ser la de hoy (un vencimiento, por ejemplo). */ hideToday?: boolean;
  /** Paso de un campo numérico: "0.01" deja cargar un 12,5 %. */ step?: string;
  /** Cómo se lee cada opción de un select, si no alcanza con ponerle mayúscula. */ optionLabels?: Record<string, string> };
export type EntityConfig = { title: string; description: string; singular: string; fields: Field[]; columns: string[]; /** Encabezados propios de este módulo, cuando el general no le queda ("Rubro" en stock, "Tipo" en bienes). */ columnTitles?: Record<string, string> };
const status = (...values: string[]): Field => ({ key: "status", label: "Estado", type: "select", options: values, required: true });
const companyLabels = { tvp: COMPANIES.tvp.legalName, constructora: COMPANIES.constructora.legalName };
// La cuenta del plan a la que se imputa y, al editar, el motivo si se la cambia (queda en el historial).
const ledger = (direction?: "ingreso" | "egreso", required = true): Field[] => [
  { key: "accountId", label: "Cuenta del plan", type: "account", relation: "accounts", direction, required, hint: direction === "ingreso" ? "Ingresos: solo cuentas CI" : direction === "egreso" ? "Egresos: CE, CC, GGD, GGI, IMP, OP o BB" : "CI si es un ingreso; cualquier otra si es un egreso" },
  { key: "accountChangeReason", label: "Motivo del cambio de cuenta", editOnly: true, hint: "Solo si cambiás la cuenta: queda en el historial" },
];
/** Los estados de obra de la especificación. Las claves son las de siempre; cambia cómo se leen. */
export const workStatusLabels: Record<string, string> = { planificada: "Pendiente de inicio", en_curso: "Activa", pausada: "Pausada", terminada: "Finalizada", cerrada: "Cerrada", cancelada: "Cancelada" };

export const entityConfig: Record<Entity, EntityConfig> = {
  clients: { title: "Clientes", description: "Contactos e historial comercial centralizado.", singular: "cliente", columns: ["name", "cuit", "contactName", "phones", "email"], fields: [
    { key:"name",label:"Razón social / nombre",required:true },{key:"cuit",label:"CUIT",required:true,placeholder:"30-12345678-9",hint:"11 dígitos, con o sin guiones"},{key:"contactName",label:"Contacto"},{key:"email",label:"Correo",type:"email"},{key:"phones",label:"Teléfonos",type:"phones"},{key:"address",label:"Dirección"},{key:"vatCondition",label:"Condición frente al IVA",type:"select",options:["","responsable_inscripto","monotributo","exento","consumidor_final","no_alcanzado"],optionLabels:{"":"Sin cargar","responsable_inscripto":"IVA Responsable Inscripto","monotributo":"Responsable Monotributo","exento":"IVA Sujeto Exento","consumidor_final":"Consumidor Final","no_alcanzado":"IVA No Alcanzado"},hint:"La pide ARCA en cada factura. Sin cargar: A = responsable inscripto, B = consumidor final"},{key:"notes",label:"Notas",type:"textarea"},
  ]},
  quotes: { title: "Cotizaciones", description: "Seguimiento completo desde el presupuesto hasta el cierre. Al aprobarla se reserva el stock disponible y lo que falta le llega a Compras.", singular: "cotización", columns: ["number","title","clientId","company","amountCents","status"], fields: [{key:"company",label:"Empresa que factura",type:"select",options:["tvp","constructora"],optionLabels:{tvp:"Trabajos Verticales Pino S.A.S.",constructora:"Constructora Pino S.R.L."},defaultValue:"tvp",required:true,hint:"Si ya se sabe; se puede cambiar al facturar"},
    {key:"number",label:"Número",placeholder:"Se genera solo al guardar"},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"title",label:"Título",required:true},{key:"description",label:"Descripción",type:"textarea"},
    // La versión la lleva el sistema: la primera cotización de un título es la 1 y cada revisión con el mismo título toma la siguiente.
    {key:"version",label:"Versión",type:"number",readOnly:true,hint:"La primera es la 1; si ya hay otra con el mismo título, sale la siguiente"},
    {key:"amountCents",label:"Importe para el cliente",type:"money",required:true},{key:"estimatedCostCents",label:"Costo estimado",type:"money"},
    // "Aprobada" y "convertida" no se eligen a mano: salen del botón Aprobar y del pase a obra.
    {...status("borrador","enviada","seguimiento","rechazada","vencida"),defaultValue:"borrador",optionLabels:{borrador:"En elaboración",enviada:"Emitida",seguimiento:"En seguimiento",aprobada:"Aprobada",rechazada:"Rechazada",vencida:"Vencida",convertida:"Pasada a obra"}},
    {key:"validUntil",label:"Válida hasta",type:"date",quickRanges:[7,14,30],defaultInDays:7,hideToday:true},{key:"attachment",label:"Presupuesto en PDF",type:"file"},
  ]},
  works: { title: "Obras", description: "Responsables, inspecciones, costos y certificados de cada trabajo. Pendiente de inicio → Activa → Finalizada → Cerrada. Tocá una obra para abrirla.", singular: "obra", columns: ["code","name","clientId","budgetCents","status"], fields: [
    {key:"code",label:"Código",required:true},{key:"name",label:"Nombre",required:true},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"quoteId",label:"Cotización origen",type:"relation",relation:"quotes"},{key:"startDate",label:"Inicio",type:"date"},{key:"endDate",label:"Fin previsto",type:"date"},{key:"budgetCents",label:"Presupuesto",type:"money",required:true},{...status("planificada","en_curso","pausada","terminada","cerrada","cancelada"),optionLabels:workStatusLabels,hint:"Cerrada: materiales, costos, facturación y cobranza conciliados"},{key:"costCenter",label:"Centro de costo"},
  ]},
  workers: { title:"Personal", description:"Legajo del personal de obra: número de legajo, DNI, teléfono, puesto y tipo de trabajo, que fija su tarifa.", singular:"integrante", columns:["fileNumber","lastName","firstName","dni","workType","position","phone"], fields:[
    {key:"fileNumber",label:"Nº de legajo",type:"number",hint:"Vacío: se asigna el siguiente"},{key:"lastName",label:"Apellido",required:true},{key:"firstName",label:"Nombre",required:true},{key:"dni",label:"DNI",placeholder:"28123456",hint:"Sin puntos"},{key:"phone",label:"Teléfono",type:"tel"},{key:"position",label:"Puesto",placeholder:"PINTOR OFICIAL, SILLETERO…"},{key:"workType",label:"Tipo de trabajo",type:"select",options:[],hint:"El habitual: fija su tarifa por hora"},{key:"category",label:"Categoría",type:"select",options:["capataz","oficial","medio_oficial","ayudante","especialista"],required:true},{key:"rateMode",label:"Cómo cobra",type:"select",options:["jornada","hora"],hint:"Por jornada o por hora"},{key:"dailyRateCents",label:"Valor del jornal",type:"money",hint:"Lo que cobra por día trabajado"},{key:"hoursPerDay",label:"Horas por jornal",type:"number",hint:"Para sacar el valor hora"},{key:"hourlyRateCents",label:"Valor hora",type:"money",hint:"Si va vacío, sale del jornal"},{key:"notes",label:"Notas",type:"textarea"},
  ]},
  suppliers: { title:"Proveedores",description:"Contactos, descuento acordado y listas de precios de cada proveedor.",singular:"proveedor",columns:["name","cuit","contactName","phone","email","discountPct"],fields:[{key:"name",label:"Nombre",required:true},{key:"cuit",label:"CUIT",placeholder:"30-12345678-9",hint:"Para el libro IVA compras"},{key:"contactName",label:"Contacto"},{key:"email",label:"Correo",type:"email"},{key:"phone",label:"Teléfono",type:"tel"},{key:"address",label:"Dirección"},{key:"discountPct",label:"Descuento acordado (%)",type:"number",step:"0.01",hint:"Se descuenta de todas sus listas de precios"},{key:"notes",label:"Notas",type:"textarea"}]},
  stock: { title:"Stock", description:"Catálogo único con lo que hay en el Depósito Central, en el Salón de Ventas y en tránsito, de qué empresa es cada existencia (CUIT propietario), lo reservado por cotizaciones aprobadas y su valorización.", singular:"material", columns:["name","category",...WAREHOUSES.map(warehouse => `qty_${warehouse.key}`),"transitQty","quantity","reservedQty","owners","lastPriceCents","valueCents"], fields:[
    {key:"name",label:"Material",required:true},{key:"sku",label:"Código interno",placeholder:"Opcional"},{key:"barcode",label:"Código de barras",placeholder:"Escanealo o dejalo vacío",hint:"El del envase, o la etiqueta que se imprime desde la Caja"},{key:"category",label:"Rubro",type:"select",options:["materiales","herramientas","seguridad","consumibles","otros"],required:true},{key:"unit",label:"Unidad de medida",type:"select",options:["unidad","kg","litro","metro","m2","m3","bolsa","balde","rollo"],required:true},...WAREHOUSES.map((warehouse): Field => ({key:`min_${warehouse.key}`,label:`Mínimo en ${warehouse.label}`,type:"number",step:"0.01",hint:"Avisa a Compras cuando baja de acá"})),{key:"supplierId",label:"Proveedor habitual",type:"relation",relation:"suppliers"},{key:"quantity",label:"Total (depósitos y tránsito)",type:"number",readOnly:true,hint:"Sale de las entradas, transferencias y salidas"},{key:"lastPriceCents",label:"Último precio",type:"money",readOnly:true,hint:"De la última lista del proveedor que lo incluyó"},{key:"valueCents",label:"Valorización",type:"money",readOnly:true},{key:"notes",label:"Notas",type:"textarea"},
  ]},
  purchases: { title:"Solicitudes y órdenes de compra",description:"Solicitud → orden de compra → recepción en el Depósito Central. Cada una queda atada a la cotización, la obra o el pedido que la originó. Todas se pueden bajar en PDF con el botón de la fila, para imprimirlas o mandárselas al proveedor.",singular:"orden",columns:["number","stage","company","description","supplierId","workId","neededBy","amountCents","status"],fields:[{key:"company",label:"Empresa que compra",type:"select",options:["tvp","constructora"],optionLabels:companyLabels,defaultValue:"tvp",required:true,hint:"Cualquiera de las dos puede comprar: a su nombre va la factura del proveedor"},{key:"number",label:"Número",placeholder:"Se genera solo al guardar"},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"quoteId",label:"Cotización de origen",type:"relation",relation:"quotes",hint:"La necesidad que la originó, si viene de una venta"},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"neededBy",label:"Fecha requerida",type:"date",hideToday:true},{key:"priority",label:"Prioridad",type:"select",options:["alta","media","baja"],defaultValue:"media"},{key:"description",label:"Detalle",type:"textarea",required:true},{key:"amountCents",label:"Importe estimado",type:"money",required:true},{key:"stage",label:"Etapa",type:"select",options:["solicitud","orden","recepcion"],required:true},status("borrador","aprobada","enviada","recibida","cancelada"),{key:"requestedDate",label:"Fecha de solicitud",type:"date",required:true},{key:"expectedDate",label:"Entrega esperada",type:"date"},{key:"receivedDate",label:"Recepción",type:"date"},{key:"receiptNotes",label:"Observaciones de recepción",type:"textarea"}]},
  expenses: { title:"Facturas de compra y gastos",description:"Las facturas de los proveedores (Factura A, C o el registro interno X), atadas a su orden de compra y al remito de lo recibido, y los costos internos de cada obra. La X cuenta para la gestión pero no va al libro IVA.",singular:"factura de compra",columns:["company","voucherType","number","supplierId","purchaseId","workId","amountCents","status"],fields:[{key:"company",label:"Empresa que compra",type:"select",options:["tvp","constructora"],optionLabels:companyLabels,hint:"A su nombre vino el comprobante. Sale de la orden de compra si no la elegís"},{key:"voucherType",label:"Comprobante",type:"select",options:["factura_a","factura_c","factura_x"],optionLabels:{factura_a:"Factura A",factura_c:"Factura C",factura_x:"Factura X (interna, no fiscal)"},hint:"Vacío: es un costo interno, no una factura del proveedor"},{key:"number",label:"Número",placeholder:"0003-00004567"},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"purchaseId",label:"Orden de compra",type:"relation",relation:"purchases",hint:"Completa sola la empresa, el proveedor y la obra"},{key:"receiptRef",label:"Remito o conformidad",placeholder:"Remito del proveedor"},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"description",label:"Descripción",required:true},{key:"category",label:"Categoría",type:"select",options:["materiales","transporte","combustible","servicios","costo_indirecto","gasto_fijo","mano_obra"],required:true},...ledger("egreso", false),{key:"netCents",label:"Neto",type:"money",hint:"Si lo cargás, el IVA (21 % en la A) y el total salen solos"},{key:"amountCents",label:"Total",type:"money",required:true},{key:"issueDate",label:"Fecha",type:"date",required:true},{key:"dueDate",label:"Vencimiento",type:"date"},status("pendiente","parcial","pagado","anulado"),{key:"paidCents",label:"Pagado",type:"money",readOnly:true,hint:"Sale de las órdenes de pago pagadas"},{key:"attachment",label:"Comprobante",type:"file"}]},
  // Las fiscales se emiten en ARCA con CAE (o se cargan las de Tango); la X se numera sola desde su talonario. Todas atadas a su cotización, hasta el recibo.
  invoices: { title:"Facturas de venta",description:"Factura A y B (fiscales: se emiten en ARCA con CAE desde acá, o se cargan las de Tango) y el comprobante interno X, que no pasa por ARCA pero cuenta en cuentas corrientes, caja y rentabilidad. Cada una atada a su cotización y a sus remitos, hasta el cobro.",singular:"factura",columns:["company","voucherType","number","quoteId","clientId","workId","amountCents","collectedCents","status"],fields:[{key:"company",label:"Empresa que factura",type:"select",options:["tvp","constructora"],optionLabels:companyLabels,defaultValue:"tvp",required:true},{key:"voucherType",label:"Tipo",type:"select",options:["factura_a","nota_debito_a","nota_credito_a","factura_b","nota_debito_b","nota_credito_b","factura_x"],optionLabels:{factura_a:"Factura A",nota_debito_a:"Nota de Débito A",nota_credito_a:"Nota de Crédito A",factura_b:"Factura B",nota_debito_b:"Nota de Débito B",nota_credito_b:"Nota de Crédito B",factura_c:"Factura C",factura_x:"Factura X (interna)"},defaultValue:"factura_a",required:true},{key:"pointOfSale",label:"Punto de venta",type:"hidden"},{key:"replacesId",label:"Sustituye a",type:"hidden"},{key:"associatedInvoiceId",label:"Factura asociada",type:"hidden"},{key:"number",label:"Número",placeholder:"0001-00000123",hint:"Lo pone ARCA al emitir; en una de Tango, su punto de venta y número"},{key:"quoteId",label:"Cotización",type:"relation",relation:"quotes",hint:"Completa solos el cliente y la obra"},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"certificateNumber",label:"Certificado"},{key:"certificateId",label:"Certificado (id)",type:"hidden"},{key:"issueDate",label:"Fecha",type:"date",required:true},{key:"dueDate",label:"Vencimiento",type:"date",hideToday:true},{key:"netCents",label:"Neto gravado",type:"money"},{key:"vatPct",label:"IVA %",type:"number",step:"0.01"},{key:"vatCents",label:"IVA",type:"money",readOnly:true},{key:"amountCents",label:"Total",type:"money",required:true},{key:"collectedCents",label:"Cobrado",type:"money",readOnly:true},{...status("pendiente","parcial","cobrada","anulada"),defaultValue:"pendiente",hint:"Sale de los recibos; elegí Anulada para anularla (una con CAE se anula con nota de crédito)"},{key:"remitoIds",label:"Remitos que factura",type:"hidden"},{key:"remitoLines",label:"Cantidades de los remitos",type:"hidden"},{key:"arcaEmit",label:"Emitir en ARCA",type:"hidden"},{key:"description",label:"Descripción",type:"textarea"},{key:"attachment",label:"PDF de Tango",type:"file"},{key:"cae",label:"CAE",readOnly:true}]},
  // Cada cobro es un recibo con número propio, aplicado a una o varias facturas.
  collections: { title:"Cobranzas y recibos",description:"Los recibos de cobro: a qué facturas se aplican, cuánto a cada una y con qué se pagó.",singular:"recibo",columns:["number","clientId","invoiceId","date","amountCents","method"],fields:[{key:"number",label:"Recibo",readOnly:true},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"invoiceId",label:"Factura",type:"relation",relation:"invoices"},{key:"date",label:"Fecha",type:"date",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"method",label:"Medio",type:"select",options:["transferencia","efectivo","cheque","retencion","otro"],required:true},{key:"cashAccountId",label:"Caja / cuenta bancaria",type:"cashAccount",relation:"cashAccounts",required:true,hint:"Del maestro de Tesorería"},{key:"reference",label:"Referencia"},{key:"notes",label:"Notas",type:"textarea"}]},
  payments: { title:"Órdenes de pago y pagos",description:"La orden de pago sale de una factura de compra; mientras está emitida no descuenta el saldo, lo hace cuando se paga. Cada pago se imputa a una cuenta del plan.",singular:"orden de pago",columns:["number","company","supplierId","expenseId","dueDate","amountCents","status","accountId"],fields:[{key:"number",label:"Número",placeholder:"Se genera solo (OP-1, OP-2…)"},{key:"company",label:"Empresa que paga",type:"select",options:["tvp","constructora"],optionLabels:companyLabels,defaultValue:"tvp",required:true},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"expenseId",label:"Factura de compra",type:"relation",relation:"expenses"},{...status("emitida","pagada","anulada"),defaultValue:"emitida",hint:"Emitida: falta pagarla. Pagada: descuenta el saldo de la factura"},{key:"date",label:"Fecha",type:"date",required:true},{key:"dueDate",label:"Vencimiento",type:"date",hideToday:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"retentionsCents",label:"Retenciones",type:"money"},{key:"method",label:"Medio",type:"select",options:["transferencia","efectivo","cheque","otro"],required:true},{key:"cashAccountId",label:"Caja / cuenta bancaria",type:"cashAccount",relation:"cashAccounts",hint:"De dónde sale la plata; obligatoria para pagarla"},...ledger("egreso"),{key:"reference",label:"Referencia"},{key:"notes",label:"Notas",type:"textarea"}]},
  checks: { title:"Cheques",description:"Cartera, vencimientos y estados de cheques.",singular:"cheque",columns:["number","bank","direction","amountCents","dueDate","status"],fields:[{key:"direction",label:"Tipo",type:"select",options:["recibido","emitido"],required:true},{key:"bank",label:"Banco",required:true},{key:"number",label:"Número",required:true},{key:"issuer",label:"Emisor"},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"dueDate",label:"Vencimiento",type:"date",required:true},status("cartera","depositado","cobrado","endosado","rechazado","emitido"),{key:"clientId",label:"Cliente",type:"relation",relation:"clients"},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"}]},
  cash: { title:"Caja y bancos",description:"Ingresos y egresos de cada caja y cuenta bancaria, imputados al plan de cuentas. Un pase entre cuentas propias se carga con su botón: deja el egreso y el ingreso atados.",singular:"movimiento",columns:["date","direction","cashAccountId","accountId","description","amountCents"],fields:[{key:"date",label:"Fecha",type:"date",required:true},{key:"direction",label:"Tipo",type:"select",options:["ingreso","egreso"],required:true},{key:"cashAccountId",label:"Caja / cuenta bancaria",type:"cashAccount",relation:"cashAccounts",required:true,hint:"Del maestro: se da de alta en Tesorería › Cajas y cuentas bancarias"},...ledger(),{key:"company",label:"Empresa",type:"select",options:["tvp","constructora"],optionLabels:companyLabels},{key:"workId",label:"Obra",type:"relation",relation:"works",hint:"Si el movimiento es de una obra"},{key:"costCenter",label:"Centro de costo"},{key:"description",label:"Descripción",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"reference",label:"Referencia"}]},
  cashAccounts: { title:"Cajas y cuentas bancarias",description:"El maestro de cajas y cuentas de las dos empresas: cada cobro, pago y movimiento elige una de acá. Una cuenta que ya se usó no se borra: se inactiva. El saldo es el inicial más lo que entró y salió desde la fecha de corte.",singular:"caja o cuenta",
    columns:["name","company","type","bank","currency","balanceCents","active"],
    fields:[{key:"company",label:"Empresa titular",type:"select",options:["tvp","constructora"],optionLabels:companyLabels,required:true},{key:"name",label:"Nombre visible",required:true,placeholder:"Banco Nación TVP, Caja pesos Constructora…",hint:"No puede repetirse, aunque se escriba distinto"},{key:"type",label:"Tipo",type:"select",options:["caja","cuenta_corriente","caja_ahorro","cuenta_dolares","otra"],optionLabels:{caja:"Caja",cuenta_corriente:"Cuenta corriente",caja_ahorro:"Caja de ahorro",cuenta_dolares:"Cuenta en dólares",otra:"Otra"},required:true},{key:"bank",label:"Banco"},{key:"currency",label:"Moneda",type:"select",options:["ARS","USD"],optionLabels:{ARS:"Pesos",USD:"Dólares"},defaultValue:"ARS"},{key:"cbu",label:"CBU / CVU"},{key:"alias",label:"Alias"},{key:"internalId",label:"Identificación interna",hint:"Si es una caja: quién la maneja, dónde está"},{key:"openingBalanceCents",label:"Saldo inicial",type:"money",hint:"Sólo Gerencia lo cambia"},{key:"openingDate",label:"Fecha de corte",type:"date",hint:"Desde acá suman los movimientos"},{key:"active",label:"Estado",type:"select",options:["true","false"],optionLabels:{true:"Activa",false:"Inactiva"},defaultValue:"true"},{key:"notes",label:"Notas",type:"textarea"}]},
  accounts: { title:"Plan de cuentas",columnTitles:{name:"Cuenta / operación"},description:"El catálogo maestro de cuentas de caja (Cuenta Cajas.xlsx). Todo ingreso va a una cuenta CI y todo egreso a una CE, CC, GGD, GGI, IMP, OP o BB. Una cuenta que no se usa más se desactiva: no se borra.",singular:"cuenta",columns:["code","name","direction","active"],fields:[{key:"code",label:"Código",type:"select",options:[...ACCOUNT_CODES],optionLabels:Object.fromEntries(ACCOUNT_CODES.map(code => [code, `${code} — ${accountCodeLabels[code]}`])),required:true},{key:"name",label:"Cuenta / operación",required:true,placeholder:"GGI - Alquileres",hint:"Con el código adelante, como en el archivo de administración"},{key:"direction",label:"Tipo",readOnly:true,hint:"Sale del código: CI es ingreso, el resto egreso"},{key:"active",label:"Estado",type:"select",options:["true","false"],optionLabels:{true:"Activa",false:"Desactivada"},defaultValue:"true",required:true},{key:"notes",label:"Notas",type:"textarea"}]},
  assets: { title:"Bienes de uso",description:"Vehículos, máquinas y equipos de la empresa, con sus services y el próximo mantenimiento programado. Tocá uno para ver su mantenimiento.",singular:"bien",columnTitles:{category:"Tipo"},columns:["name","sector","category","identifier","responsible","currentReading","nextDueDate","status"],fields:[{key:"name",label:"Nombre",required:true,placeholder:"Camioneta Hilux, Hidrolavadora…"},{key:"sector",label:"Sector",type:"select",options:["albanileria","altura","pintura","aislamiento","general"],optionLabels:{albanileria:"Albañilería",altura:"Trabajos en altura",pintura:"Pintura",aislamiento:"Aislamiento / Espuma / Impermeabilización",general:"General (utilitarios)"},defaultValue:"general",required:true,hint:"General: lo que se usa en cualquier obra o sector (autos, andamios…)"},{key:"category",label:"Tipo",type:"select",options:["vehiculo","maquinaria","herramienta","equipo","informatica","inmueble","otro"],optionLabels:{vehiculo:"Vehículo",informatica:"Informática"},defaultValue:"vehiculo",required:true},{key:"identifier",label:"Patente / nº de serie",placeholder:"AB 123 CD"},{key:"brand",label:"Marca"},{key:"model",label:"Modelo"},{key:"year",label:"Año",type:"number"},{key:"purchaseDate",label:"Fecha de compra",type:"date"},{key:"valueCents",label:"Valor",type:"money",hint:"Lo que costó o lo que vale hoy"},{key:"responsible",label:"Responsable",placeholder:"Quién lo usa o lo tiene a cargo"},{key:"location",label:"Dónde está",placeholder:"Depósito, obra, taller…"},{...status("activo","en_reparacion","fuera_de_servicio","baja"),defaultValue:"activo"},{key:"meterUnit",label:"Cómo se mide el uso",type:"select",options:["km","horas","ninguno"],optionLabels:{km:"Kilómetros",horas:"Horas de uso",ninguno:"No se mide"},defaultValue:"ninguno"},{key:"currentReading",label:"Lectura actual",type:"number",hint:"Km del tablero u horas del horómetro"},{key:"nextDueDate",label:"Próximo mantenimiento",type:"date",readOnly:true,hint:"Sale de lo programado en Mantenimiento"},{key:"notes",label:"Notas",type:"textarea"},{key:"attachment",label:"Papeles (título, seguro, VTV)",type:"file"}]},
  tasks: { title:"Tareas y pendientes",description:"Pendientes operativos y administrativos del equipo.",singular:"tarea",columns:["title","type","assigneeRole","assigneeName","dueDate","status"],fields:[{key:"title",label:"Título",required:true},{key:"description",label:"Descripción",type:"textarea"},{key:"type",label:"Tipo",type:"select",options:["general","facturar_certificado","cobranza","vencimiento"],required:true},status("pendiente","en_curso","completada"),{key:"dueDate",label:"Vencimiento",type:"date"},{key:"assigneeRole",label:"Área responsable",type:"select",options:["gerencia","arquitecto","auxiliar","administracion","compras","ventas","contador"]},{key:"assigneeId",label:"Persona asignada",type:"user",hint:"Opcional: si va a nombre de alguien"}]},
};

export const columnLabels: Record<string,string> = { name:"Nombre",contactName:"Contacto",phone:"Teléfono",email:"Correo",number:"Número",title:"Título",clientId:"Cliente",supplierId:"Proveedor",workId:"Obra",invoiceId:"Factura",expenseId:"Gasto",amountCents:"Importe",budgetCents:"Presupuesto",status:"Estado",progress:"Avance",description:"Descripción",date:"Fecha",method:"Medio",bank:"Banco",direction:"Tipo",dueDate:"Vencimiento",type:"Tipo",assigneeRole:"Área",assigneeName:"Persona",code:"Código",cuit:"CUIT",phones:"Teléfonos",quantity:"Total",...Object.fromEntries(WAREHOUSES.map(warehouse => [`qty_${warehouse.key}`, warehouse.short])),minQuantity:"Mínimo",avgCostCents:"Costo promedio",sector:"Sector",company:"Empresa",fileNumber:"Legajo",position:"Puesto",workType:"Tipo de trabajo",quoteId:"Cotización",collectedCents:"Cobrado",cashAccountId:"Caja / cuenta",balanceCents:"Saldo",currency:"Moneda",openingBalanceCents:"Saldo inicial",voucherType:"Tipo",netCents:"Neto",vatCents:"IVA",lastPriceCents:"Último precio",valueCents:"Valorización",category:"Rubro",unit:"Unidad",firstName:"Nombre",lastName:"Apellido",dni:"DNI",dailyRateCents:"Valor del jornal",hoursPerDay:"Horas por jornal",hourlyRateCents:"Valor hora",rateMode:"Cómo cobra",discountPct:"Descuento",barcode:"Código de barras",accountId:"Cuenta del plan",active:"Estado",transitQty:"En tránsito",reservedQty:"Reservado",owners:"Propietario",purchaseId:"Orden de compra",neededBy:"Requerida",stage:"Etapa",retentionsCents:"Retenciones",identifier:"Patente / serie",responsible:"Responsable",currentReading:"Uso",nextDueDate:"Próximo mantenimiento",brand:"Marca",model:"Modelo" };
