import type { Entity } from "./constants";
import { WAREHOUSES } from "./warehouses";

export type Field = { key: string; label: string; type?: "text"|"email"|"tel"|"number"|"money"|"date"|"textarea"|"select"|"relation"|"user"|"file"|"phones"; /** Lo calcula el sistema: se muestra pero no se edita a mano. */ readOnly?: boolean; required?: boolean; options?: string[]; relation?: Entity; placeholder?: string; hint?: string; /** Atajos "7 / 14 / 30 días" en los campos de fecha. */ quickRanges?: number[];
  /** Con qué viene cargado el campo al crear un registro nuevo. */ defaultValue?: string;
  /** Igual que `defaultValue` pero para fechas: hoy + N días. */ defaultInDays?: number;
  /** Saca el atajo "Hoy": no toda fecha puede ser la de hoy (un vencimiento, por ejemplo). */ hideToday?: boolean;
  /** Paso de un campo numérico: "0.01" deja cargar un 12,5 %. */ step?: string;
  /** Cómo se lee cada opción de un select, si no alcanza con ponerle mayúscula. */ optionLabels?: Record<string, string> };
export type EntityConfig = { title: string; description: string; singular: string; fields: Field[]; columns: string[]; /** Encabezados propios de este módulo, cuando el general no le queda ("Rubro" en stock, "Tipo" en bienes). */ columnTitles?: Record<string, string> };
const status = (...values: string[]): Field => ({ key: "status", label: "Estado", type: "select", options: values, required: true });

export const entityConfig: Record<Entity, EntityConfig> = {
  clients: { title: "Clientes", description: "Contactos e historial comercial centralizado.", singular: "cliente", columns: ["name", "cuit", "contactName", "phones", "email"], fields: [
    { key:"name",label:"Razón social / nombre",required:true },{key:"cuit",label:"CUIT",required:true,placeholder:"30-12345678-9",hint:"11 dígitos, con o sin guiones"},{key:"contactName",label:"Contacto"},{key:"email",label:"Correo",type:"email"},{key:"phones",label:"Teléfonos",type:"phones"},{key:"address",label:"Dirección"},{key:"notes",label:"Notas",type:"textarea"},
  ]},
  quotes: { title: "Ventas y cotizaciones", description: "Seguimiento completo desde el presupuesto hasta el cierre.", singular: "cotización", columns: ["number","title","clientId","amountCents","status"], fields: [
    {key:"number",label:"Número",placeholder:"Se genera solo al guardar"},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"title",label:"Título",required:true},{key:"description",label:"Descripción",type:"textarea"},
    // La versión la lleva el sistema: la primera cotización de un título es la 1 y cada revisión con el mismo título toma la siguiente.
    {key:"version",label:"Versión",type:"number",readOnly:true,hint:"La primera es la 1; si ya hay otra con el mismo título, sale la siguiente"},
    {key:"amountCents",label:"Importe para el cliente",type:"money",required:true},{key:"estimatedCostCents",label:"Costo estimado",type:"money"},
    // "Aprobada" y "convertida" no se eligen a mano: salen del botón Aprobar y del pase a obra.
    {...status("borrador","enviada","seguimiento","rechazada","vencida"),defaultValue:"borrador"},
    {key:"validUntil",label:"Válida hasta",type:"date",quickRanges:[7,14,30],defaultInDays:7,hideToday:true},{key:"attachment",label:"Presupuesto en PDF",type:"file"},
  ]},
  works: { title: "Obras", description: "Responsables, inspecciones, costos y certificados de cada trabajo. Tocá una obra para abrirla.", singular: "obra", columns: ["code","name","clientId","budgetCents","status"], fields: [
    {key:"code",label:"Código",required:true},{key:"name",label:"Nombre",required:true},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"quoteId",label:"Cotización origen",type:"relation",relation:"quotes"},{key:"startDate",label:"Inicio",type:"date"},{key:"endDate",label:"Fin previsto",type:"date"},{key:"budgetCents",label:"Presupuesto",type:"money",required:true},status("planificada","en_curso","pausada","terminada","cancelada"),{key:"costCenter",label:"Centro de costo"},
  ]},
  workers: { title:"Personal asignado", description:"Legajo del personal de obra: número de legajo, DNI, teléfono, puesto y tipo de trabajo, que fija su tarifa.", singular:"integrante", columns:["fileNumber","lastName","firstName","dni","workType","position","phone"], fields:[
    {key:"fileNumber",label:"Nº de legajo",type:"number",hint:"Vacío: se asigna el siguiente"},{key:"lastName",label:"Apellido",required:true},{key:"firstName",label:"Nombre",required:true},{key:"dni",label:"DNI",placeholder:"28123456",hint:"Sin puntos"},{key:"phone",label:"Teléfono",type:"tel"},{key:"position",label:"Puesto",placeholder:"PINTOR OFICIAL, SILLETERO…"},{key:"workType",label:"Tipo de trabajo",type:"select",options:[],hint:"El habitual: fija su tarifa por hora"},{key:"category",label:"Categoría",type:"select",options:["capataz","oficial","medio_oficial","ayudante","especialista"],required:true},{key:"rateMode",label:"Cómo cobra",type:"select",options:["jornada","hora"],hint:"Por jornada o por hora"},{key:"dailyRateCents",label:"Valor del jornal",type:"money",hint:"Lo que cobra por día trabajado"},{key:"hoursPerDay",label:"Horas por jornal",type:"number",hint:"Para sacar el valor hora"},{key:"hourlyRateCents",label:"Valor hora",type:"money",hint:"Si va vacío, sale del jornal"},{key:"notes",label:"Notas",type:"textarea"},
  ]},
  suppliers: { title:"Proveedores",description:"Contactos, descuento acordado y listas de precios de cada proveedor.",singular:"proveedor",columns:["name","contactName","phone","email","discountPct"],fields:[{key:"name",label:"Nombre",required:true},{key:"contactName",label:"Contacto"},{key:"email",label:"Correo",type:"email"},{key:"phone",label:"Teléfono",type:"tel"},{key:"address",label:"Dirección"},{key:"discountPct",label:"Descuento acordado (%)",type:"number",step:"0.01",hint:"Se descuenta de todas sus listas de precios"},{key:"notes",label:"Notas",type:"textarea"}]},
  stock: { title:"Stock", description:"Materiales en el Depósito Central y en el Salón de Ventas, con su costo y su valorización.", singular:"material", columns:["name","category",...WAREHOUSES.map(warehouse => `qty_${warehouse.key}`),"quantity","lastPriceCents","valueCents"], fields:[
    {key:"name",label:"Material",required:true},{key:"sku",label:"Código interno",placeholder:"Opcional"},{key:"barcode",label:"Código de barras",placeholder:"Escanealo o dejalo vacío",hint:"El del envase, o la etiqueta que se imprime desde la Caja"},{key:"category",label:"Rubro",type:"select",options:["materiales","herramientas","seguridad","consumibles","otros"],required:true},{key:"unit",label:"Unidad de medida",type:"select",options:["unidad","kg","litro","metro","m2","m3","bolsa","balde","rollo"],required:true},...WAREHOUSES.map((warehouse): Field => ({key:`min_${warehouse.key}`,label:`Mínimo en ${warehouse.label}`,type:"number",step:"0.01",hint:"Avisa a Compras cuando baja de acá"})),{key:"supplierId",label:"Proveedor habitual",type:"relation",relation:"suppliers"},{key:"quantity",label:"Total entre depósitos",type:"number",readOnly:true,hint:"Sale de las entradas, pases y salidas"},{key:"lastPriceCents",label:"Último precio",type:"money",readOnly:true,hint:"De la última lista del proveedor que lo incluyó"},{key:"valueCents",label:"Valorización",type:"money",readOnly:true},{key:"notes",label:"Notas",type:"textarea"},
  ]},
  purchases: { title:"Órdenes de compra",description:"Solicitudes, órdenes y recepción de materiales y servicios. Las que se cierran desde el buscador de precios traen su PDF.",singular:"orden",columns:["number","description","supplierId","workId","amountCents","status"],fields:[{key:"number",label:"Número",placeholder:"Se genera solo al guardar"},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"description",label:"Detalle",type:"textarea",required:true},{key:"amountCents",label:"Importe estimado",type:"money",required:true},{key:"stage",label:"Etapa",type:"select",options:["solicitud","orden","recepcion"],required:true},status("borrador","aprobada","enviada","recibida","cancelada"),{key:"requestedDate",label:"Fecha de solicitud",type:"date",required:true},{key:"expectedDate",label:"Entrega esperada",type:"date"},{key:"receivedDate",label:"Recepción",type:"date"},{key:"receiptNotes",label:"Observaciones de recepción",type:"textarea"}]},
  expenses: { title:"Compras y gastos",description:"Costos directos, indirectos y gastos fijos.",singular:"gasto",columns:["description","supplierId","workId","amountCents","status"],fields:[{key:"number",label:"Número interno"},{key:"description",label:"Descripción",required:true},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"category",label:"Categoría",type:"select",options:["materiales","transporte","combustible","servicios","costo_indirecto","gasto_fijo","mano_obra"],required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"issueDate",label:"Fecha",type:"date",required:true},{key:"dueDate",label:"Vencimiento",type:"date"},status("pendiente","parcial","pagado","anulado"),{key:"paidCents",label:"Pagado",type:"money"},{key:"attachment",label:"Comprobante",type:"file"}]},
  // Las facturas se emiten en Tango y se cargan acá, atadas a su cotización, para seguirlas hasta el recibo.
  invoices: { title:"Facturación",description:"Las facturas emitidas en Tango, cargadas a mano y atadas a su cotización para seguirlas hasta el cobro.",singular:"factura",columns:["company","number","quoteId","clientId","workId","amountCents","collectedCents","status"],fields:[{key:"company",label:"Empresa que factura",type:"select",options:["tvp","constructora"],optionLabels:{tvp:"Trabajos Verticales Pino S.A.S.",constructora:"Constructora Pino S.R.L."},defaultValue:"tvp",required:true},{key:"voucherType",label:"Tipo",type:"select",options:["factura_a","factura_b","factura_c"],optionLabels:{factura_a:"Factura A",factura_b:"Factura B",factura_c:"Factura C"},defaultValue:"factura_a",required:true},{key:"number",label:"Número",required:true,placeholder:"0001-00000123",hint:"Punto de venta y número, como en Tango"},{key:"quoteId",label:"Cotización",type:"relation",relation:"quotes",hint:"Completa solos el cliente y la obra"},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"certificateNumber",label:"Certificado"},{key:"issueDate",label:"Fecha",type:"date",required:true},{key:"dueDate",label:"Vencimiento",type:"date",hideToday:true},{key:"netCents",label:"Neto gravado",type:"money"},{key:"vatPct",label:"IVA %",type:"number",step:"0.01"},{key:"vatCents",label:"IVA",type:"money",readOnly:true},{key:"amountCents",label:"Total",type:"money",required:true},{key:"collectedCents",label:"Cobrado",type:"money",readOnly:true},{...status("pendiente","parcial","cobrada","anulada"),defaultValue:"pendiente",hint:"Sale de los recibos; elegí Anulada para anularla"},{key:"description",label:"Descripción",type:"textarea"},{key:"attachment",label:"PDF de Tango",type:"file"}]},
  // Cada cobro es un recibo con número propio, aplicado a una o varias facturas.
  collections: { title:"Cobranzas y recibos",description:"Los recibos de cobro: a qué facturas se aplican, cuánto a cada una y con qué se pagó.",singular:"recibo",columns:["number","clientId","invoiceId","date","amountCents","method"],fields:[{key:"number",label:"Recibo",readOnly:true},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"invoiceId",label:"Factura",type:"relation",relation:"invoices"},{key:"date",label:"Fecha",type:"date",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"method",label:"Medio",type:"select",options:["transferencia","efectivo","cheque","retencion","otro"],required:true},{key:"account",label:"Cuenta / caja"},{key:"reference",label:"Referencia"},{key:"notes",label:"Notas",type:"textarea"}]},
  payments: { title:"Cuentas a pagar",description:"Pagos y órdenes vinculados a proveedores y gastos.",singular:"pago",columns:["supplierId","expenseId","date","amountCents","method"],fields:[{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"expenseId",label:"Gasto",type:"relation",relation:"expenses"},{key:"date",label:"Fecha",type:"date",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"method",label:"Medio",type:"select",options:["transferencia","efectivo","cheque","otro"],required:true},{key:"account",label:"Cuenta / caja"},{key:"reference",label:"Referencia"},{key:"notes",label:"Notas",type:"textarea"}]},
  checks: { title:"Cheques",description:"Cartera, vencimientos y estados de cheques.",singular:"cheque",columns:["number","bank","direction","amountCents","dueDate","status"],fields:[{key:"direction",label:"Tipo",type:"select",options:["recibido","emitido"],required:true},{key:"bank",label:"Banco",required:true},{key:"number",label:"Número",required:true},{key:"issuer",label:"Emisor"},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"dueDate",label:"Vencimiento",type:"date",required:true},status("cartera","depositado","cobrado","endosado","rechazado","emitido"),{key:"clientId",label:"Cliente",type:"relation",relation:"clients"},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"}]},
  cash: { title:"Caja y bancos",description:"Movimientos internos y conciliación operativa de cuentas.",singular:"movimiento",columns:["date","direction","account","description","amountCents"],fields:[{key:"date",label:"Fecha",type:"date",required:true},{key:"direction",label:"Tipo",type:"select",options:["ingreso","egreso"],required:true},{key:"account",label:"Caja / cuenta bancaria",required:true},{key:"category",label:"Categoría",required:true},{key:"description",label:"Descripción",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"reference",label:"Referencia"}]},
  assets: { title:"Bienes de uso",description:"Vehículos, máquinas y equipos de la empresa, con sus services y el próximo mantenimiento programado. Tocá uno para ver su mantenimiento.",singular:"bien",columnTitles:{category:"Tipo"},columns:["name","category","identifier","responsible","currentReading","nextDueDate","status"],fields:[{key:"name",label:"Nombre",required:true,placeholder:"Camioneta Hilux, Hidrolavadora…"},{key:"category",label:"Tipo",type:"select",options:["vehiculo","maquinaria","herramienta","equipo","informatica","inmueble","otro"],optionLabels:{vehiculo:"Vehículo",informatica:"Informática"},defaultValue:"vehiculo",required:true},{key:"identifier",label:"Patente / nº de serie",placeholder:"AB 123 CD"},{key:"brand",label:"Marca"},{key:"model",label:"Modelo"},{key:"year",label:"Año",type:"number"},{key:"purchaseDate",label:"Fecha de compra",type:"date"},{key:"valueCents",label:"Valor",type:"money",hint:"Lo que costó o lo que vale hoy"},{key:"responsible",label:"Responsable",placeholder:"Quién lo usa o lo tiene a cargo"},{key:"location",label:"Dónde está",placeholder:"Depósito, obra, taller…"},{...status("activo","en_reparacion","fuera_de_servicio","baja"),defaultValue:"activo"},{key:"meterUnit",label:"Cómo se mide el uso",type:"select",options:["km","horas","ninguno"],optionLabels:{km:"Kilómetros",horas:"Horas de uso",ninguno:"No se mide"},defaultValue:"ninguno"},{key:"currentReading",label:"Lectura actual",type:"number",hint:"Km del tablero u horas del horómetro"},{key:"nextDueDate",label:"Próximo mantenimiento",type:"date",readOnly:true,hint:"Sale de lo programado en Mantenimiento"},{key:"notes",label:"Notas",type:"textarea"},{key:"attachment",label:"Papeles (título, seguro, VTV)",type:"file"}]},
  tasks: { title:"Tareas y pendientes",description:"Pendientes operativos y administrativos del equipo.",singular:"tarea",columns:["title","type","assigneeRole","assigneeName","dueDate","status"],fields:[{key:"title",label:"Título",required:true},{key:"description",label:"Descripción",type:"textarea"},{key:"type",label:"Tipo",type:"select",options:["general","facturar_certificado","cobranza","vencimiento"],required:true},status("pendiente","en_curso","completada"),{key:"dueDate",label:"Vencimiento",type:"date"},{key:"assigneeRole",label:"Área responsable",type:"select",options:["gerencia","arquitecto","auxiliar","administracion","compras","ventas","contador"]},{key:"assigneeId",label:"Persona asignada",type:"user",hint:"Opcional: si va a nombre de alguien"}]},
};

export const columnLabels: Record<string,string> = { name:"Nombre",contactName:"Contacto",phone:"Teléfono",email:"Correo",number:"Número",title:"Título",clientId:"Cliente",supplierId:"Proveedor",workId:"Obra",invoiceId:"Factura",expenseId:"Gasto",amountCents:"Importe",budgetCents:"Presupuesto",status:"Estado",progress:"Avance",description:"Descripción",date:"Fecha",method:"Medio",bank:"Banco",direction:"Tipo",dueDate:"Vencimiento",type:"Tipo",assigneeRole:"Área",assigneeName:"Persona",code:"Código",cuit:"CUIT",phones:"Teléfonos",quantity:"Total",...Object.fromEntries(WAREHOUSES.map(warehouse => [`qty_${warehouse.key}`, warehouse.short])),minQuantity:"Mínimo",avgCostCents:"Costo promedio",company:"Empresa",fileNumber:"Legajo",position:"Puesto",workType:"Tipo de trabajo",quoteId:"Cotización",collectedCents:"Cobrado",voucherType:"Tipo",netCents:"Neto",vatCents:"IVA",lastPriceCents:"Último precio",valueCents:"Valorización",category:"Rubro",unit:"Unidad",firstName:"Nombre",lastName:"Apellido",dni:"DNI",dailyRateCents:"Valor del jornal",hoursPerDay:"Horas por jornal",hourlyRateCents:"Valor hora",rateMode:"Cómo cobra",discountPct:"Descuento",barcode:"Código de barras",identifier:"Patente / serie",responsible:"Responsable",currentReading:"Uso",nextDueDate:"Próximo mantenimiento",brand:"Marca",model:"Modelo" };
