import type { Entity } from "./constants";

export type Field = { key: string; label: string; type?: "text"|"email"|"tel"|"number"|"money"|"date"|"textarea"|"select"|"relation"|"file"|"phones"; required?: boolean; options?: string[]; relation?: Entity; placeholder?: string; hint?: string; /** Atajos "7 / 14 / 30 días" en los campos de fecha. */ quickRanges?: number[] };
export type EntityConfig = { title: string; description: string; singular: string; fields: Field[]; columns: string[] };
const status = (...values: string[]): Field => ({ key: "status", label: "Estado", type: "select", options: values, required: true });

export const entityConfig: Record<Entity, EntityConfig> = {
  clients: { title: "Clientes", description: "Contactos e historial comercial centralizado.", singular: "cliente", columns: ["name", "cuit", "contactName", "phones", "email"], fields: [
    { key:"name",label:"Razón social / nombre",required:true },{key:"cuit",label:"CUIT",required:true,placeholder:"30-12345678-9",hint:"11 dígitos, con o sin guiones"},{key:"contactName",label:"Contacto"},{key:"email",label:"Correo",type:"email"},{key:"phones",label:"Teléfonos",type:"phones"},{key:"address",label:"Dirección"},{key:"notes",label:"Notas",type:"textarea"},
  ]},
  quotes: { title: "Ventas y cotizaciones", description: "Seguimiento completo desde el presupuesto hasta el cierre.", singular: "cotización", columns: ["number","title","clientId","amountCents","status"], fields: [
    {key:"number",label:"Número",placeholder:"Se genera solo al guardar"},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"title",label:"Título",required:true},{key:"description",label:"Descripción",type:"textarea"},{key:"version",label:"Versión",type:"number",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"estimatedCostCents",label:"Costo estimado",type:"money"},status("borrador","enviada","seguimiento","aprobada","rechazada","vencida","convertida"),{key:"validUntil",label:"Válida hasta",type:"date",quickRanges:[7,14,30]},{key:"attachment",label:"Presupuesto en PDF",type:"file"},
  ]},
  works: { title: "Obras", description: "Avance, responsables, costos y certificados de cada trabajo.", singular: "obra", columns: ["code","name","clientId","progress","budgetCents","status"], fields: [
    {key:"code",label:"Código",required:true},{key:"name",label:"Nombre",required:true},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"quoteId",label:"Cotización origen",type:"relation",relation:"quotes"},{key:"startDate",label:"Inicio",type:"date"},{key:"endDate",label:"Fin previsto",type:"date"},{key:"budgetCents",label:"Presupuesto",type:"money",required:true},{key:"progress",label:"Avance (%)",type:"number",required:true},status("planificada","en_curso","pausada","terminada","cancelada"),{key:"costCenter",label:"Centro de costo"},
  ]},
  suppliers: { title:"Proveedores",description:"Contactos y cuenta corriente de proveedores.",singular:"proveedor",columns:["name","contactName","phone","email"],fields:[{key:"name",label:"Nombre",required:true},{key:"contactName",label:"Contacto"},{key:"email",label:"Correo",type:"email"},{key:"phone",label:"Teléfono",type:"tel"},{key:"address",label:"Dirección"},{key:"notes",label:"Notas",type:"textarea"}]},
  purchases: { title:"Órdenes de compra",description:"Solicitudes, órdenes y recepción de materiales y servicios.",singular:"orden",columns:["number","description","supplierId","workId","amountCents","status"],fields:[{key:"number",label:"Número",required:true},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"description",label:"Detalle",type:"textarea",required:true},{key:"amountCents",label:"Importe estimado",type:"money",required:true},{key:"stage",label:"Etapa",type:"select",options:["solicitud","orden","recepcion"],required:true},status("borrador","aprobada","enviada","recibida","cancelada"),{key:"requestedDate",label:"Fecha de solicitud",type:"date",required:true},{key:"expectedDate",label:"Entrega esperada",type:"date"},{key:"receivedDate",label:"Recepción",type:"date"},{key:"receiptNotes",label:"Observaciones de recepción",type:"textarea"}]},
  expenses: { title:"Compras y gastos",description:"Costos directos, indirectos y gastos fijos.",singular:"gasto",columns:["description","supplierId","workId","amountCents","status"],fields:[{key:"number",label:"Número interno"},{key:"description",label:"Descripción",required:true},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"category",label:"Categoría",type:"select",options:["materiales","transporte","combustible","servicios","costo_indirecto","gasto_fijo","mano_obra"],required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"issueDate",label:"Fecha",type:"date",required:true},{key:"dueDate",label:"Vencimiento",type:"date"},status("pendiente","parcial","pagado","anulado"),{key:"paidCents",label:"Pagado",type:"money"},{key:"attachment",label:"Comprobante",type:"file"}]},
  invoices: { title:"Facturación administrativa",description:"Comprobantes emitidos externamente, sin integración fiscal.",singular:"factura",columns:["number","clientId","workId","amountCents","status"],fields:[{key:"number",label:"Número",required:true},{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"workId",label:"Obra",type:"relation",relation:"works"},{key:"certificateNumber",label:"Certificado"},{key:"description",label:"Descripción",type:"textarea"},{key:"issueDate",label:"Fecha",type:"date",required:true},{key:"dueDate",label:"Vencimiento",type:"date"},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"collectedCents",label:"Cobrado",type:"money"},status("pendiente","parcial","cobrada","anulada"),{key:"attachment",label:"Comprobante",type:"file"}]},
  collections: { title:"Cuentas a cobrar",description:"Cobros parciales y saldo de clientes.",singular:"cobro",columns:["clientId","invoiceId","date","amountCents","method"],fields:[{key:"clientId",label:"Cliente",type:"relation",relation:"clients",required:true},{key:"invoiceId",label:"Factura",type:"relation",relation:"invoices"},{key:"date",label:"Fecha",type:"date",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"method",label:"Medio",type:"select",options:["transferencia","efectivo","cheque","retencion","otro"],required:true},{key:"account",label:"Cuenta / caja"},{key:"reference",label:"Referencia"},{key:"notes",label:"Notas",type:"textarea"}]},
  payments: { title:"Cuentas a pagar",description:"Pagos y órdenes vinculados a proveedores y gastos.",singular:"pago",columns:["supplierId","expenseId","date","amountCents","method"],fields:[{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"},{key:"expenseId",label:"Gasto",type:"relation",relation:"expenses"},{key:"date",label:"Fecha",type:"date",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"method",label:"Medio",type:"select",options:["transferencia","efectivo","cheque","otro"],required:true},{key:"account",label:"Cuenta / caja"},{key:"reference",label:"Referencia"},{key:"notes",label:"Notas",type:"textarea"}]},
  checks: { title:"Cheques",description:"Cartera, vencimientos y estados de cheques.",singular:"cheque",columns:["number","bank","direction","amountCents","dueDate","status"],fields:[{key:"direction",label:"Tipo",type:"select",options:["recibido","emitido"],required:true},{key:"bank",label:"Banco",required:true},{key:"number",label:"Número",required:true},{key:"issuer",label:"Emisor"},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"dueDate",label:"Vencimiento",type:"date",required:true},status("cartera","depositado","cobrado","endosado","rechazado","emitido"),{key:"clientId",label:"Cliente",type:"relation",relation:"clients"},{key:"supplierId",label:"Proveedor",type:"relation",relation:"suppliers"}]},
  cash: { title:"Caja y bancos",description:"Movimientos internos y conciliación operativa de cuentas.",singular:"movimiento",columns:["date","direction","account","description","amountCents"],fields:[{key:"date",label:"Fecha",type:"date",required:true},{key:"direction",label:"Tipo",type:"select",options:["ingreso","egreso"],required:true},{key:"account",label:"Caja / cuenta bancaria",required:true},{key:"category",label:"Categoría",required:true},{key:"description",label:"Descripción",required:true},{key:"amountCents",label:"Importe",type:"money",required:true},{key:"reference",label:"Referencia"}]},
  tasks: { title:"Tareas",description:"Pendientes operativos y administrativos del equipo.",singular:"tarea",columns:["title","type","assigneeRole","dueDate","status"],fields:[{key:"title",label:"Título",required:true},{key:"description",label:"Descripción",type:"textarea"},{key:"type",label:"Tipo",type:"select",options:["general","facturar_certificado","cobranza","vencimiento"],required:true},status("pendiente","en_curso","completada"),{key:"dueDate",label:"Vencimiento",type:"date"},{key:"assigneeRole",label:"Asignar a",type:"select",options:["gerencia","arquitecto","auxiliar","administracion","compras","ventas","contador"]}]},
};

export const columnLabels: Record<string,string> = { name:"Nombre",contactName:"Contacto",phone:"Teléfono",email:"Correo",number:"Número",title:"Título",clientId:"Cliente",supplierId:"Proveedor",workId:"Obra",invoiceId:"Factura",expenseId:"Gasto",amountCents:"Importe",budgetCents:"Presupuesto",status:"Estado",progress:"Avance",description:"Descripción",date:"Fecha",method:"Medio",bank:"Banco",direction:"Tipo",dueDate:"Vencimiento",type:"Tipo",assigneeRole:"Responsable",code:"Código",cuit:"CUIT",phones:"Teléfonos" };
