"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { BriefcaseBusiness, Download, Edit3, Eye, Plus, Search, Trash2, Upload, X } from "lucide-react";
import Link from "next/link";
import type { Entity } from "@/lib/constants";
import { entityConfig, columnLabels, type Field } from "@/lib/entity-config";
import { date, money, titleCase } from "@/lib/format";

type Item = Record<string, unknown> & { _id: string };
export function EntityManager({ entity }: { entity: Entity }) {
  const config = entityConfig[entity]; const fileRef=useRef<HTMLInputElement>(null); const [items,setItems]=useState<Item[]>([]); const [relations,setRelations]=useState<Record<string,Item[]>>({}); const [search,setSearch]=useState(""); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<Item|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load = useCallback(async () => { setLoading(true); const r=await fetch(`/api/records/${entity}?limit=100&search=${encodeURIComponent(search)}`); const d=await r.json(); if(r.ok) setItems(d.items); else setError(d.error); setLoading(false); },[entity,search]);
  useEffect(()=>{ const timer=setTimeout(load,250); return()=>clearTimeout(timer);},[load]);
  const relationEntities=useMemo(()=>[...new Set(config.fields.filter(f=>f.relation).map(f=>f.relation!))],[config.fields]);
  useEffect(()=>{ Promise.all(relationEntities.map(async rel=>[rel,(await (await fetch(`/api/records/${rel}?limit=100`)).json()).items||[]] as const)).then(values=>setRelations(Object.fromEntries(values))); },[relationEntities]);
  function relationLabel(field:string,value:unknown){ const def=config.fields.find(f=>f.key===field); const row=def?.relation?relations[def.relation]?.find(x=>x._id===String(value)):null; return row ? String(row.name||row.title||row.number) : value ? "…" : "—"; }
  function display(key:string,value:unknown){ if(key.endsWith("Cents")) return money(Number(value||0)); if(key==="progress") return `${value||0}%`; if(key.toLowerCase().includes("date")) return date(value as string); if(key.endsWith("Id")) return relationLabel(key,value); if(key==="status"||key==="type"||key==="method"||key==="direction"||key==="assigneeRole") return <span className={`badge ${value}`}>{titleCase(String(value||""))}</span>; return value ? String(value) : "—"; }
  function open(item?:Item){setEditing(item||null);setModal(true);setError("");}
  async function remove(item:Item){ if(!confirm(`¿Eliminar este ${config.singular}? Esta acción quedará auditada.`))return; const r=await fetch(`/api/records/${entity}/${item._id}`,{method:"DELETE"}); if(r.ok)load(); else setError((await r.json()).error); }
  async function convertQuote(item:Item){const code=prompt("Código para la nueva obra:",`OB-${String(item.number||"")}`);if(!code)return;const name=prompt("Nombre de la obra:",String(item.title||""));if(!name)return;const r=await fetch(`/api/quotes/${item._id}/convert`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,name})});const d=await r.json();if(!r.ok)setError(d.error);else load()}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);const body:Record<string,unknown>={};for(const field of config.fields){let value:unknown=form.get(field.key);if(field.type==="file"){if(value instanceof File&&value.size){const upload=new FormData();upload.set("file",value);const response=await fetch("/api/uploads",{method:"POST",body:upload});const result=await response.json();if(!response.ok)return setError(result.error||"No se pudo subir el archivo");value=result.path}else value=editing?.[field.key]||""}else if(field.type==="money")value=Math.round(Number(value||0)*100);else if(field.type==="number")value=Number(value||0);body[field.key]=value}const url=editing?`/api/records/${entity}/${editing._id}`:`/api/records/${entity}`;const r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return setError(d.error||"No se pudo guardar");setModal(false);load();}
  async function importFile(file?:File){if(!file)return;setLoading(true);setError("");const form=new FormData();form.set("file",file);const r=await fetch(`/api/import/${entity}`,{method:"POST",body:form});const d=await r.json();if(!r.ok)setError(d.error);else if(d.errors?.length)setError(`Se importaron ${d.imported} de ${d.total} filas. ${d.errors.length} tuvieron errores.`);await load();if(fileRef.current)fileRef.current.value="";}
  return <><div className="page-heading"><div><p className="eyebrow">GESTIÓN</p><h1>{config.title}</h1><p>{config.description}</p></div><button className="primary-btn" onClick={()=>open()}><Plus size={18}/> Nuevo {config.singular}</button></div><div className="toolbar"><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Buscar en ${config.title.toLowerCase()}…`}/></div><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>importFile(e.target.files?.[0])}/><button className="secondary-btn" onClick={()=>fileRef.current?.click()}><Upload size={17}/> Importar</button><a className="secondary-btn" href={`/api/reports/export?entity=${entity}`}><Download size={17}/> Exportar CSV</a></div>{error&&<div className="notice error">{error}</div>}<section className="table-panel"><div className="table-scroll"><table><thead><tr>{config.columns.map(c=><th key={c}>{columnLabels[c]||c}</th>)}<th/></tr></thead><tbody>{items.map(item=><tr key={item._id}>{config.columns.map(c=><td key={c}>{display(c,item[c])}</td>)}<td className="row-actions">{entity==="works"&&<Link title="Abrir obra" href={`/app/works/${item._id}`}><Eye size={16}/></Link>}{entity==="quotes"&&item.status==="aprobada"&&<button title="Convertir en obra" onClick={()=>convertQuote(item)}><BriefcaseBusiness size={16}/></button>}<button title="Editar" onClick={()=>open(item)}><Edit3 size={16}/></button><button title="Eliminar" onClick={()=>remove(item)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>{loading?<div className="loading-state">Cargando…</div>:!items.length&&<div className="empty-state compact"><p>No hay registros para mostrar.</p><button onClick={()=>open()}>Crear {config.singular}</button></div>}</section>{modal&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setModal(false)}/><section className="modal"><header><div><p className="eyebrow">{editing?"EDITAR":"NUEVO REGISTRO"}</p><h2>{editing?`Editar ${config.singular}`:`Nuevo ${config.singular}`}</h2></div><button className="icon-btn" onClick={()=>setModal(false)}><X/></button></header><form onSubmit={submit}><div className="form-grid">{config.fields.map(field=><FormField key={field.key} field={field} value={editing?.[field.key]} relationItems={field.relation?relations[field.relation]||[]:[]}/>)}</div>{error&&<p className="form-error">{error}</p>}<footer><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Cancelar</button><button className="primary-btn">Guardar</button></footer></form></section></div>}</>;
}

function FormField({field,value,relationItems}:{field:Field;value:unknown;relationItems:Item[]}){const common={name:field.key,required:field.required,defaultValue:field.type==="money"?Number(value||0)/100:field.type==="date"&&value?new Date(String(value)).toISOString().slice(0,10):String(value??"")};return <label className={field.type==="textarea"?"wide":""}><span>{field.label}{field.required&&" *"}</span>{field.type==="textarea"?<textarea {...common}/>:field.type==="select"?<select {...common}><option value="">Seleccionar…</option>{field.options?.map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select>:field.type==="relation"?<select {...common}><option value="">Seleccionar…</option>{relationItems.map(x=><option key={x._id} value={x._id}>{String(x.name||x.title||x.number)}</option>)}</select>:field.type==="file"?<><input name={field.key} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.xlsx"/>{value&&<a href={String(value)} target="_blank" rel="noreferrer">Ver archivo actual</a>}</>:<input {...common} type={field.type==="money"||field.type==="number"?"number":field.type||"text"} step={field.type==="money"?"0.01":field.key==="progress"?"1":undefined} min={field.type==="money"||field.type==="number"?"0":undefined} placeholder={field.placeholder}/>}</label>}
