import mongoose from "mongoose";

const uri=process.env.MONGODB_URI?.trim();const interval=Math.max(60000,Number(process.env.WORKER_INTERVAL_MS||300000));const timeout=Math.max(1000,Number(process.env.MONGODB_SERVER_SELECTION_TIMEOUT_MS||5000));
if(!uri)throw new Error("Falta MONGODB_URI");
const Task=mongoose.models.Task||mongoose.model("Task",new mongoose.Schema({title:String,description:String,type:String,status:String,dueDate:Date,assigneeRole:String,relatedType:String,relatedId:mongoose.Schema.Types.ObjectId},{timestamps:true}));
const Invoice=mongoose.models.Invoice||mongoose.model("Invoice",new mongoose.Schema({number:String,dueDate:Date,status:String},{strict:false}));
const Check=mongoose.models.Check||mongoose.model("Check",new mongoose.Schema({number:String,dueDate:Date,status:String},{strict:false}));
const Notification=mongoose.models.Notification||mongoose.model("Notification",new mongoose.Schema({title:String,body:String,kind:String,href:String,roles:[String],status:String,remindAt:Date,dedupeKey:{type:String,index:true}},{timestamps:true}));
const Asset=mongoose.models.Asset||mongoose.model("Asset",new mongoose.Schema({name:String,identifier:String,status:String,plans:[{title:String,dueDate:Date,status:String}]},{strict:false}));
const Quote=mongoose.models.Quote||mongoose.model("Quote",new mongoose.Schema({number:String,validUntil:Date,status:String},{strict:false}));
// COT-9: la cotización vence sola al pasar validUntil. Las aprobadas quedan afuera a propósito:
// vencer una cotización ya aprobada bloquearía la creación de la obra sin que nadie se entere.
async function expireQuotes(now){const{modifiedCount}=await Quote.updateMany({validUntil:{$lt:now},status:{$in:["borrador","enviada","seguimiento"]}},{$set:{status:"vencida"}});if(modifiedCount)console.log(`[worker] ${modifiedCount} cotizaciones vencidas`);}
// Un aviso por hecho: si ya existe con la misma clave, no se duplica.
async function ensureNotification(dedupeKey,title,body,kind,href,roles){await Notification.updateOne({dedupeKey},{$setOnInsert:{dedupeKey,title,body,kind,href,roles:[...new Set([...roles,"gerencia"])],status:"pendiente"}},{upsert:true})}
async function ensureTask(title,type,relatedType,relatedId,dueDate){await Task.updateOne({type,relatedType,relatedId,status:{$ne:"completada"}},{$setOnInsert:{title,type,relatedType,relatedId,dueDate,status:"pendiente",assigneeRole:"administracion"}},{upsert:true})}
// Bienes de uso: lo programado por fecha avisa 14 días antes (ASSET_NOTICE_DAYS en src/lib/assets.ts) y deja
// la tarea a Compras y logística, una por mantenimiento. Lo que vence por km u horas lo avisa la app al cargar la lectura.
async function remindAssetPlans(now){const horizon=new Date(now.getTime()+14*86400000);const assets=await Asset.find({status:{$ne:"baja"},plans:{$elemMatch:{status:"pendiente",dueDate:{$lte:horizon}}}}).lean();const fmt=new Intl.DateTimeFormat("es-AR",{timeZone:"UTC"});await Promise.all(assets.flatMap(asset=>(asset.plans||[]).filter(plan=>plan.status==="pendiente"&&plan.dueDate&&new Date(plan.dueDate)<=horizon).map(async plan=>{const title=`Mantenimiento: ${plan.title} — ${asset.identifier?`${asset.name} (${asset.identifier})`:asset.name}`;const body=`${new Date(plan.dueDate)<now?"Venció":"Vence"} el ${fmt.format(new Date(plan.dueDate))}.`;await Task.updateOne({relatedType:"asset_plans",relatedId:plan._id,status:{$ne:"completada"}},{$setOnInsert:{title,description:`${body} Registralo en Bienes de uso cuando esté hecho.`,type:"vencimiento",status:"pendiente",assigneeRole:"compras",relatedType:"asset_plans",relatedId:plan._id,dueDate:plan.dueDate}},{upsert:true});await ensureNotification(`asset-plan-${plan._id}`,title,body,"vencimiento","/app/assets",["compras","administracion"])})))}
async function run(){const now=new Date();const horizon=new Date(now.getTime()+7*86400000);await expireQuotes(now);await remindAssetPlans(now);const[invoices,checks]=await Promise.all([Invoice.find({dueDate:{$lte:horizon},status:{$in:["pendiente","parcial"]}}).lean(),Check.find({dueDate:{$lte:horizon},status:{$in:["cartera","emitido"]}}).lean()]);await Promise.all([...invoices.map(x=>ensureTask(`Revisar cobranza de factura ${x.number}`,"cobranza","invoices",x._id,x.dueDate)),...checks.map(x=>ensureTask(`Cheque ${x.number} próximo a vencer`,"vencimiento","checks",x._id,x.dueDate)),...invoices.map(x=>ensureNotification(`invoice-due-${x._id}`,`Factura ${x.number} por vencer`,`Vence el ${new Intl.DateTimeFormat("es-AR",{timeZone:"America/Argentina/Buenos_Aires"}).format(new Date(x.dueDate))}.`,"cobranza","/app/invoices",["administracion"])),...checks.map(x=>ensureNotification(`check-due-${x._id}`,`Cheque ${x.number} por vencer`,`Vence el ${new Intl.DateTimeFormat("es-AR",{timeZone:"America/Argentina/Buenos_Aires"}).format(new Date(x.dueDate))}.`,"vencimiento","/app/checks",["administracion"]))]);console.log(`[worker] ${new Date().toISOString()} alertas actualizadas`)}
try { await mongoose.connect(uri,{maxPoolSize:5,serverSelectionTimeoutMS:timeout}); } catch (error) { const message=error instanceof Error?error.message.split("\n")[0]:"error desconocido"; console.error(`[worker] MongoDB no disponible: ${message}`); process.exit(1); }
await run();setInterval(()=>run().catch(error=>console.error("[worker]",error)),interval);
process.on("SIGINT",async()=>{await mongoose.disconnect();process.exit(0)});process.on("SIGTERM",async()=>{await mongoose.disconnect();process.exit(0)});
